const express = require("express")
const app = express()
const userRoutes = require("./routes/userRoutes")

app.set('view engine', 'ejs')
app.use(express.static("public"))
app.use(express.json())
app.use(express.urlencoded({extended: false}))
app.use("/user", userRoutes)
app.listen(8000, ()=>{console.log("server started")})